name: Real-time Monitor

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  # schedule:
  #   - cron: '*/20 * * * *'

jobs:
  check-news:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: pip install -r requirements.txt
        
      - name: Run Monitor Mode
        env:
          # 主机器人配置 (Monitor模式虽然不用，但保留以防万一)
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          
          # 👇 注入监控机器人配置
          TG_BOT_TOKEN_MONITOR: ${{ secrets.TG_BOT_TOKEN_MONITOR }}
          TG_CHAT_ID_MONITOR: ${{ secrets.TG_CHAT_ID_MONITOR }}
          
          GLOBAL_NEWS_RSS: ${{ secrets.GLOBAL_NEWS_RSS }}
          CUSTOM_NEWS_RSS: ${{ secrets.CUSTOM_NEWS_RSS }}
        run: python main.py monitor
